# Step 1 - Builder
FROM golang:alpine AS builder

# Install git
RUN apk update && apk add --no-cache git

WORKDIR $GOPATH/src/wesleysaraujo/fullcycle
COPY . .

# Fetch dependencies
RUN go get -d -v

# Build the binary
RUN go build -o /go/bin/fullcycle

# Step 2 - Run binary
FROM scratch

COPY --from=builder /go/bin/fullcycle /go/bin/fullcycle

CMD ["/go/bin/fullcycle"]